# Generated by Django 6.0.6 on 2026-07-07 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('students', '0003_department_alter_student_gender_student_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='departments.department'),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
