# Generated by Django 6.0.6 on 2026-07-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_department_delete_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='roll_number',
            field=models.CharField(help_text='Unique roll no. of a student', max_length=20, null=True, unique=True),
        ),
    ]
