# Generated by Django 6.0.6 on 2026-07-20 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('students', '0005_student_roll_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['roll_number', 'name']},
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['name'], name='student_name_index'),
        ),
    ]
