# Generated by Django 6.0.6 on 2026-07-22 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enrollments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.DecimalField(decimal_places=2, max_digits=5)),
                ('maximum_marks', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('percentage', models.DecimalField(decimal_places=2, editable=False, max_digits=5)),
                ('letter_grade', models.CharField(editable=False, max_length=2)),
                ('grade_point', models.DecimalField(decimal_places=2, editable=False, max_digits=5)),
                ('result', models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail')], editable=False, max_length=5)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='enrollments.enrollment')),
            ],
            options={
                'ordering': ['enrollment'],
                'constraints': [models.CheckConstraint(condition=models.Q(('maximum_marks__gt', 0)), name='grade_maximum_marks_positive'), models.CheckConstraint(condition=models.Q(('marks_obtained__gte', 0)), name='grade_marks_obtained_non_negative'), models.CheckConstraint(condition=models.Q(('marks_obtained__lte', models.F('maximum_marks'))), name='grade_marks_cannot_exceed_max')],
            },
        ),
    ]
