# Generated by Django 6.0.6 on 2026-08-08 15:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Audit',
            new_name='AuditLog',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_content_4c2ead_idx',
            old_name='audit_audit_content_e61349_idx',
        ),
    ]
