# Generated by Django 6.0.6 on 2026-07-20 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enrollments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LEFT', 'Left'), ('LATE', 'Late')], default='PRESENT', max_length=10)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='enrollments.enrollment')),
            ],
            options={
                'ordering': ['-date', 'enrollment'],
                'constraints': [models.UniqueConstraint(fields=('enrollment', 'date'), name='Unique_enrollment_date')],
            },
        ),
    ]
